### ISSUE TITLE
2.x todo

### ISSUE THREAD

**Issue by kbond** [kbond/foundry-next#2]
- [x] Persistence
   - [x] Factory - additional static methods
   - [x] RepositoryDecorator - additional method and assertions
- [ ] ORM
  - [x] ManyToOne
  - [x] OneToMany
  - [x] ManyToMany (owning)
  - [x] ManyToMany (inverse)
  - [x] OneToOne (owning)
  - [x] Cascade for above relationships
  - [ ] "Rich entities"
- [x] Mongo
  - [x] EmbedOne
  - [x] EmbedMany
- [ ] Maker's
- [x] Collection
  - [x] Sequences
  - [x] asDataProvider
- [x] Story state and pools
- [x] "Delay Flush"
- [x] Using array of factories for mapper/instantiator: `SomeFactory::createOne(['items' => [SomeOtherFactory::new()]])`
- [x] Invokable stories" (rename `global_stories` back to `global_state`)
- [x] ~`always_force_properties` not working?~
- [x] `Test/Factories::disablePersist()`/`enablePersist()` - as global functions
- [ ] `RepositoryDecorator::find()` parity: https://github.com/zenstruck/foundry/blob/925eab3c2bbb2cea5e3c3b9c5af29c32cb0ceb99/src/RepositoryProxy.php#L306 (https://github.com/zenstruck/foundry/pull/432)
- [x] (re)merge `Instantiator`/`Mapper` into `Hydrator`
